### ISSUE TITLE
broken, please fix

### ISSUE THREAD

**Issue by KraXen72** [luimu64/pc-nitro-spoof#10]
this plugin no longer works. please fix it. thank you

**Comment by luimu64** [comment]
skill issue

**Comment by KraXen72** [comment]
what

**Comment by KraXen72** [comment]
sorry, what does "skill issue" mean exactly

**Comment by luimu64** [comment]
It means that this is a non-issue and even if it was real issue I would not be able to anything about it with your so useful information. You already made issue about this and I answered.

**Comment by KraXen72** [comment]
?? i don't know how the plugin works. its broken now because of a recent discord update. please fix it. if you need more information, please let me know.  can send you console screenshots etc whatever you need for fixing the plugin.

**Comment by KraXen72** [comment]
followed instructions in readme. works now.
