### ISSUE TITLE
Implement escaping (for servers with NQN bot)

### ISSUE THREAD

**Issue by Delphox** [luimu64/pc-nitro-spoof#5]
Whenever you have the time, can you add the possibility of escaping emojis with \, so we can take advantage of the usability patcher for servers that have NQN. It'd work like this:

• when an emoji is escaped like this `\<:aaaa:123>`, add a condition that bypasses the "replace with emoji url" function (and the "put at the end one with linebreak" one as well, I guess that already happens by design), and also removes the singular \ when sendMessage is caught. It'd post the raw emoji as `<:aaaa:123>`. The `<:aaaa:123>` will fail to render due to lack of Nitro and will be replaced accordingly by NQN.

• when an emoji is escaped with \\, still remove just one \ as per above, so the message gets sent as `\<:aaaa:123>` which would be a regular escaped emoji, which will be ignored by NQN and will be left unrendered.

Here's a demo of how it'd work in practice, done with a bit of video editing.

https://user-images.githubusercontent.com/5883538/143059540-1a51b64b-e7cd-4e94-bb03-4efe67ccb7c3.mp4

**Comment by luimu64** [comment]
Easiest implementation for this would be just changing the extraction regex to only match emojis without \ in front of them. The thing is I tested with [this](https://regex101.com/r/pPRvQp/1) supposedly working regex and there was no change in the behavior. There is other ways to achieve this but this would be so good and I feel like this is some stupid goosemod bug or other unrelated issue again.

If the nqn-escape branch works for you I'll merge it, if not I'll think of some uglier solution.

**Comment by Delphox** [comment]
That does half the job yea, although the regex should be `/(?<!\\)<a?:(\w+):(\d+)>/ig` (the one on that repo doesn't work in the middle of the message).

The other half would be matching a singular backslash in front of the message and removing it, so it works with NQN. Cuz NQN doesn't match escaped emojis (the idea here is to have a "plugin escape" first, and if you really want to escape for NQN as well, you'd do double escape.

This should be fine to do as a separate function independent from the main one now that the main plugin function won't match emojis preceded by \

**Comment by luimu64** [comment]
Ok, I got simple implementation now which bypasses the replacing and removes \\ (discord adds extra \) so nqn catches them. Still no escaping for nqn, and my method needs more checks since it now removes all \\ in the message. Will work on this some more tomorrow probably.

**Comment by Delphox** [comment]
Thank you! With that foundation you made I managed to get something working with regex replace here. I'll make a PR into that branch so you can take a look.
