### ISSUE TITLE
broken.

### ISSUE THREAD

**Issue by KraXen72** [luimu64/pc-nitro-spoof#6]
using goosemod and it's broken.
autocomplete doesen't work and emotes don't send

**Comment by luimu64** [comment]
1. be sure that you actually have it installed
2. restart discord ctrl + r
3. if still not working open developer console using ctrl + shift + i and send screenshot what shows up when you try to send emoji

**Comment by KraXen72** [comment]
![image](https://user-images.githubusercontent.com/21956756/143294479-fc553751-9e2d-4116-924d-15f08e06716b.png)
autcomplete works now, but when i send an emoji it instantly reverts to its shortcode
![Capture_2021_m11 d24_19;28](https://user-images.githubusercontent.com/21956756/143294656-b2f1eeca-1f95-49f9-b851-06e64819b6ea.gif)

**Comment by luimu64** [comment]
That's not an issue with the plugin but Goosemod. Happens to me very often, you just:
1. uninstall the plugin
2. refresh the plugin store 
3. reinstall the plugin
4. refresh discord for good measure

Jimmy explained it here https://github.com/luimu64/nitro-spoof/pull/3#issuecomment-970453310
